name: Build and deploy JAR app to Azure Web App - bigmall

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build sem rodar testes
        working-directory: ./api
        run: mvn clean install -DskipTests

      - name: Upload do artefato para o deploy
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}.api/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C39D5F3327354B03B2853C853477745B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_60E1E189987E4BACAED1F859B4C6199E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_82CAD8A0168E45B3A5ECF321EECFCA71 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bigmall'
          slot-name: 'Production'
          package: '*.jar'
