name: Build and deploy JAR app to Azure Web App - ibmec-ecommerce-sexta-mall

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build sem rodar testes
        working-directory: ./api
        run: mvn clean install -DskipTests

      - name: Upload do artefato para o deploy
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Baixar artefato do job de build
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7813730647474FA79192BBDA3310BC79 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_016BA931D3D34DD6AFC8F9296DB27F86 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2B29C71216A84C10B67A6174DAC5B7B9 }}

      - name: Deploy para Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ibmec-ecommerce-sexta-mall'
          slot-name: 'Production'
          package: '*.jar'
